#!/bin/bash

SOFTWARE_HOME=~/Software

function Usage(){
cat << HELP

Usage: gom <version>

Example:
    gom go1.15
    gom go1.16
HELP
}

function List(){
ls "${SOFTWARE_HOME}" | grep -E "go.+"
}

if [ -z "$1" ]; then
    Usage
    exit 0
fi

case "$1" in
"-h"|"--help")
    Usage
;;
"-l"|"--list")
    List
;;
*)
    ln -snf "${SOFTWARE_HOME}/$1" "${SOFTWARE_HOME}/go"
    go version
esac
