#!/bin/bash

SOFTWARE_HOME=~/Software

function Usage(){
cat << HELP

Usage: nom <version>

Example:
    nom node-v18.19.0-x64
    nom node-v20.10.0-x64
HELP
}

function List(){
ls "${SOFTWARE_HOME}" | grep -E "node.+"
}

if [ -z "$1" ]; then
    Usage
    exit 0
fi

case "$1" in
"-h"|"--help")
    Usage
;;
"-l"|"--list")
    List
;;
*)
    ln -snf "${SOFTWARE_HOME}/$1" "${SOFTWARE_HOME}/node"
    node -V
esac
