#!/bin/bash

server=1.1.1.1

case "$1" in
  "stop")
    sudo wg-quick down wg0
    ;;
  *)
    today=$(date +%y%m%d)
    port=$(echo -n ${today} | awk '{print substr($1,2,6)}')
    sudo sed -i "s/Endpoint = ${server}:[0-9]\+$/Endpoint = ${server}:${port}/g" /etc/wireguard/wg0.conf
    sudo wg-quick up wg0
    ;;
esac
